In [13]:
import torch
import torch.nn as nn

# Giả sử đầu vào có kích thước (batch_size=2, feature_dim=4)
x = torch.tensor([[1.0, 2.0, 3.0, 4.0], [2.0, 3.0, 4.0, 5.0]])

# Khởi tạo LayerNorm với số chiều là 4 (tương ứng với feature_dim)
layer_norm = nn.LayerNorm(4)

# Áp dụng Layer Normalization
output = layer_norm(x)
print(output)


tensor([[-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416]],
       grad_fn=<NativeLayerNormBackward0>)


In [14]:
import torch
import torch.nn as nn

# Giả sử batch_size=3, feature_dim=4
x = torch.tensor([[1.0, 2.0, 3.0, 4.0], 
                  [2.0, 3.0, 4.0, 5.0], 
                  [3.0, 4.0, 5.0, 6.0]])

# BatchNorm1d chuẩn hóa theo batch size (m=3, d=4)
bn = nn.BatchNorm1d(num_features=4)

# Áp dụng Batch Normalization
output = bn(x)
print(output)


tensor([[-1.2247, -1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247,  1.2247]],
       grad_fn=<NativeBatchNormBackward0>)


In [15]:
import torch
import torch.nn as nn

# Tạo một Embedding layer có 10 từ (vocab_size = 10), mỗi từ được nhúng thành vector 3 chiều.
embedding = nn.Embedding(10, 3)

# Một batch có 2 mẫu, mỗi mẫu gồm 4 từ (biểu diễn bằng chỉ số)
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])

# Truy xuất embedding vector cho các từ trong batch
output = embedding(input)
print(output)  # (batch_size=2, seq_len=4, embedding_dim=3)


tensor([[[ 0.7562,  0.2520,  0.7577],
         [-0.8483,  0.8329, -0.1455],
         [-1.2316, -0.8314, -1.2689],
         [-2.5400, -0.1638,  1.3766]],

        [[-1.2316, -0.8314, -1.2689],
         [-0.0308, -0.9525,  0.8229],
         [-0.8483,  0.8329, -0.1455],
         [ 1.0613, -0.2722, -1.0300]]], grad_fn=<EmbeddingBackward0>)


In [16]:
import torch
import torch.nn as nn
import math
import model as md
d_model = 512   # Số chiều của vector nhúng
seq_len = 100   # Độ dài tối đa của chuỗi
dropout = 0.1   # Dropout rate

# Khởi tạo PositionalEncoding
pos_enc = md.PositionalEncoding(d_model, seq_len, dropout)

# Tạo batch dữ liệu giả (batch_size=2, seq_len=10, d_model=512)
x = torch.randn(2, 10, d_model)

# Áp dụng Positional Encoding
output = pos_enc(x)
print(output)  # (2, 10, 512)


tensor([[[-0.0000,  1.7753, -0.5893,  ...,  0.6431,  0.3392,  1.3575],
         [ 0.0000,  0.7511,  2.0425,  ...,  1.5869,  0.8418,  1.9228],
         [ 0.0000,  1.1335, -1.8044,  ..., -1.2578,  0.6375,  0.4899],
         ...,
         [-1.3164, -1.3258,  0.0000,  ...,  1.7872,  2.8883, -0.6204],
         [ 0.4701,  1.1750,  0.2216,  ...,  1.4030, -1.0140,  2.3272],
         [ 1.4968, -0.0000,  0.6190,  ...,  1.2874, -2.9233,  0.7029]],

        [[-0.6325,  0.0000,  0.0000,  ...,  0.0000,  0.9860,  0.6005],
         [ 2.4013, -0.0000, -0.3913,  ..., -0.9646, -0.6615, -0.0000],
         [ 1.0304, -2.4809,  0.8951,  ...,  1.9867, -1.0253, -2.6687],
         ...,
         [ 0.6421, -0.8278,  0.7687,  ...,  0.0000,  0.2262,  1.1699],
         [ 0.9326, -0.2455,  0.9482,  ...,  2.1814, -0.8421,  1.5301],
         [ 2.4433, -2.6634,  1.5769,  ...,  1.1734, -0.4784,  2.1249]]])
